# Generated by Django 5.2.7 on 2025-11-15 17:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_configuracionsistema_alerta_stock_bajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionsistema',
            old_name='email_notificacion',
            new_name='email_notificaciones',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='notificaciones_stock',
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='categoria_predeterminada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_predeterminada', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='frecuencia_reportes',
            field=models.CharField(default='semanal', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='hora_notificaciones',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='telefono_restaurante',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
