# Generated by Django 5.2.7 on 2025-11-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_email_notificacion_configuracionsistema_email_notificaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='control_caducidad',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='notif_pedidos_pendientes',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='notif_productos_caducados',
        ),
    ]
